[build]
  publish = "."
  functions = "netlify/functions"

# Scopes the 26-second timeout to all functions globally using valid syntax
[functions]
  [functions.timeout]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200